language: python
python:
  - "2.7"
before_install:
  - echo $TRAVIS_OS_NAME
install:
  - pip install pylint
script:
  - pylint --rcfile "$WORKSPACE/build_tools/pylint.rc" -f parseable reflectivity_ui/interfaces/data_handling reflectivity_ui/interfaces/event_handlers || exit 0
